version: '3'
services:

  mongodb:
    container_name: "mongodb"
    image: "mongo"
    ports:
      - 27017:27017
  
  neo4j:
    container_name: "neo4j"
    image: "neo4j"
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=none
    volumes:
      # Sostituire il path
      - "/Users/dannydenovi/Documents/University/Second Year/Basi Di Dati NoSQL/ProgettoDBNoSQL/csv:/var/lib/neo4j/import"
